@webapi_HostAddress = http://localhost:5001
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImpiYWxscyIsIm5iZiI6MTcxNTAwMjA5NCwiZXhwIjoxNzE1MjYxMjk0LCJpYXQiOjE3MTUwMDIwOTQsImF1ZCI6Imh0dHA6Ly9sb2NhbGhvc3Q6NTAwMCJ9.R_XyPEym3Hg3gcwPlNqRyfk2v-xnruSdyWftdMimljY

GET {{webapi_HostAddress}}/project/
Authorization: Bearer {{jwt}}
Accept: application/json
###

POST {{webapi_HostAddress}}/project/
###

GET {{webapi_HostAddress}}/department/
Accept: application/json
###

GET {{webapi_HostAddress}}/user/jballs
Authorization: Bearer {{jwt}}
Accept: application/json
###

POST {{webapi_HostAddress}}/user/create/
Content-Type: application/json

{
    "username": "jjjball2",
    "email": "j@dddd.com",
    "hashed_password": "password"
}
###

POST {{webapi_HostAddress}}/user/login/
Content-Type: application/json

{
    "username": "jballs"
}
###

# v               