@webapi_HostAddress = http://localhost:5001
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1bmlxdWVfbmFtZSI6ImhlbGxvd29ybGQiLCJuYmYiOjE3MTUxNzY5MDYsImV4cCI6MTcxNTQzNjEwNiwiaWF0IjoxNzE1MTc2OTA2LCJhdWQiOiJodHRwOi8vbG9jYWxob3N0OjUwMDAifQ.OKZe_1oUtqsO_WCEAsxYMOAwiOn212ZfZuzCwsOnFMs

GET {{webapi_HostAddress}}/project/
Authorization: Bearer {{jwt}}
Accept: application/json
###

POST {{webapi_HostAddress}}/user/create/
Content-Type: application/json

{
    "username": "helloworld",
    "email": "helloworld@gmail.com",
    "password": "password",
    "firstName": "hello",
    "lastName": "world"
}
###

POST {{webapi_HostAddress}}/user/login/
Content-Type: application/json

{
    "username": "helloworld",
    "password": "password"
}
###

POST {{webapi_HostAddress}}/department/
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name": "bigworlddepartment",
    "description": "spodermun",
    "visibilty": true
}

# v                