@webapi_HostAddress = http://localhost:5001
@jwt = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiI2IiwidW5pcXVlX25hbWUiOiJoZWxsb3dvcmxkIiwibmJmIjoxNzE1MzU4ODk4LCJleHAiOjE3MTU2MTgwOTgsImlhdCI6MTcxNTM1ODg5OCwiYXVkIjoiaHR0cDovL2xvY2FsaG9zdDo1MDAwIn0.Qar6le0VQNNIvc5VJBaTNoYlOlXIW009i6QwYtU6jJE


POST {{webapi_HostAddress}}/user/create/
Content-Type: application/json

{
    "username": "helloworld",
    "email": "helloworld@gmail.com",
    "password": "password",
    "firstName": "hello",
    "lastName": "world"
}
### creates an user

POST {{webapi_HostAddress}}/user/login/
Content-Type: application/json

{
    "username": "helloworld",
    "password": "password"
}
### logs in user based on credentials

POST {{webapi_HostAddress}}/department/
Authorization: Bearer {{jwt}}
Content-Type: application/json

{
    "name": "bigworlddepartment",
    "description": "spodermun",
    "visibility": true
}
### creates department

GET {{webapi_HostAddress}}/department?department_id=6
Authorization: Bearer {{jwt}}
Accept: application/json
### gets department based on department id
 
GET {{webapi_HostAddress}}/department/all
Authorization: Bearer {{jwt}}
Accept: application/json
### get all departments the user is in

POST {{webapi_HostAddress}}/deparment/invite?department


// FOR TESTING ONLY //
PUT {{webapi_HostAddress}}/department/testingadd?user_id=6&department_id=3
Authorization: Bearer {{jwt}}
### add user to department

# v                       